const mongoose = require('mongoose');
const { Schema } = mongoose;

const paymentRecordSchema = new Schema(
  {
    user: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    amount: {
      type: Number,
      required: [true, 'Payment amount is required'],
    },
    currency: {
      type: String,
      default: 'NGN', // Or your primary currency
    },
    paymentFor: {
      // Example: "Annual Dues 2024", "Street Light Levy Q1"
      type: String,
      required: [true, 'Purpose of payment is required'],
      trim: true,
    },
    // Optional: If you have predefined types of dues/levies
    // duesLevyType: {
    //   type: Schema.Types.ObjectId,
    //   ref: 'DuesLevyType', // You would need to create this model
    // },
    paymentMethod: {
      type: String,
      enum: ['Flutterwave', 'Bank Transfer', 'Paystack', 'Manual'], // Replaced Haystack with Paystack
      required: [true, 'Payment method is required'],
    },
    status: {
      type: String,
      enum: ['pending', 'successful', 'failed', 'verifying', 'cancelled'],
      default: 'pending',
    },
    proofOfPaymentUrl: {
      // For Bank Transfer or Manual payments
      type: String,
      trim: true,
    },
    transactionReference: {
      // Unique reference generated by your system before sending to payment gateway
      type: String,
      required: true,
      unique: true,
      trim: true,
    },
    flutterwaveTransactionId: {
      // ID returned by Flutterwave after successful payment
      type: String,
      trim: true,
    },
    paystackTransactionId: { // Added for Paystack
      type: String,
      trim: true,
    },
    receiptUrl: {
      // URL/path to the generated PDF receipt
      type: String,
      trim: true,
    },
    paymentDate: {
      // Actual date payment was made/confirmed
      type: Date,
      default: Date.now,
    },
    verifiedBy: {
      // Admin/Executive who verified a manual or bank transfer payment
      type: Schema.Types.ObjectId,
      ref: 'User',
    },
    verificationDate: {
      type: Date,
    },
    // Additional notes or details about the payment
    notes: {
        type: String,
        trim: true
    }
  },
  {
    timestamps: true, // Adds createdAt and updatedAt
  }
);

// Indexing for faster queries
paymentRecordSchema.index({ user: 1, status: 1 });
paymentRecordSchema.index({ transactionReference: 1 });
paymentRecordSchema.index({ paymentFor: 1 });

const PaymentRecord = mongoose.model('PaymentRecord', paymentRecordSchema);

module.exports = PaymentRecord;
